### ISSUE TITLE
Erro na responsividade

### ISSUE THREAD

**Issue by juanrtalmeida** [devsnorte/devsnorte-landing-page#13]
| Erro  | Imagem do erro | 
|--------- |---------------|
|Espaço para o texto texto muito pequeno entre `980px` e `820px` | ![image](https://github.com/devsnorte/devsnorte-landing-page/assets/75220133/cfbcf194-1403-480f-9a3b-0e780f8aede7) |
|Design com erro de design entre `820px` e `632px` | ![image](https://github.com/devsnorte/devsnorte-landing-page/assets/75220133/6f838c56-bcc6-460b-9612-69cb3b5aa091) |
| Design com erro entre `1200px` e `1020px` de largura da tela |![image](https://github.com/devsnorte/devsnorte-landing-page/assets/75220133/62e22970-56d0-4405-b7c0-ad63ab824f9b)) |

**Comment by thauska** [comment]
@all-contributors add @juanrtalmeida for bug.
