### ISSUE TITLE
Conteúdo sumindo

### ISSUE THREAD

**Issue by ecsistem** [devsnorte/devsnorte-landing-page#15]
Conteúdo que não devia sumir no mobile está sumindo. texto e a sessão de eventos sumiu devido o _overflow-hidden_ .  A correção de responsividade tem que ser no container

**Comment by thauska** [comment]
Essa atividade irás executar?

**Comment by thauska** [comment]
@all-contributors add @ecsistem for bug

**Comment by ecsistem** [comment]
@thauska  Essa task não vou pegar

**Comment by juanrtalmeida** [comment]
@ecsistem consegue verificar se ainda existe esse problema agora que a responsividade foi corrigida?

**Comment by ecsistem** [comment]
@thauska @iagocavalcante  problema corrigido já
