### ISSUE TITLE
Newsletter

### ISSUE THREAD

**Issue by DaywisonSilva** [devsnorte/devsnorte-landing-page#5]
Implementar Newsletter
![image](https://github.com/devsnorte/devsnorte-landing-page/assets/54292958/67d4cdb4-b40f-46ff-972a-b9ed92679f68)

https://www.figma.com/file/eenBVFzu17zB259Xw6OUwu/Devs-Norte---Site-Redesign?type=design&node-id=22%3A109&mode=design&t=sP25Jybc7AV4XWCo-1

**Comment by cleisoncarlos** [comment]
ta integrada com alguma ferramenta, ou posso fazer só a estrutura ?

**Comment by iagocavalcante** [comment]
Pode só fazer a estrutura, ainda não está integrado com nenhuma plataforma

**Comment by cleisoncarlos** [comment]
#31
