### ISSUE TITLE
Adicionar uma seção para parcerias 

### ISSUE THREAD

**Issue by ecsistem** [devsnorte/devsnorte-landing-page#51]

**Comment by Kenny4297** [comment]
Olá a todos, acredito que posso ajudar com este problema. Vocês podem me atribuir a ele?

**Comment by iagocavalcante** [comment]
@all-contributors add @Kenny4297 for code

**Comment by Kenny4297** [comment]
Você pode me dar as informações necessárias que você quer que eu adicione?

**Comment by ecsistem** [comment]
@Kenny4297 Acredito que seria bom colocar algo nesse estilo: https://ui.aceternity.com/components/animated-tooltip, que tenha o nome de quem contribuiu e link do github ou fazer e formato de card.
adiciona um titulo(Contribuidores) também 

ex:
<link do github>
[Foto]
[Edson Costa]
[Frontend Engineer]
</link do github>

<link do github>
[Foto]
[Kedgard Cordero]
[Software Engineer]
</link do github>

**Comment by ecsistem** [comment]
@thauska Passa os parceiros para ele, so lembro da [Faculdade VINCIT]

**Comment by thauska** [comment]
Jetbrains: https://www.jetbrains.com/company/brand/
Faculdade Vincit: https://www.faculdadevincit.edu.br/
Fanhero: https://fanhero.com/pt-br/
Amazonia Online: https://amazoniaonline.com.br/

**Comment by thauska** [comment]
@iagocavalcante temos mais algum?!

**Comment by iagocavalcante** [comment]
> @iagocavalcante temos mais algum?!

Iidopterlabs: https://www.idopterlabs.com.br/

**Comment by Kenny4297** [comment]
Olá a todos. Quando tento executar a aplicação para resolver este problema, estou recebendo erros de hidratação que se referem ao pacote de tradução i18. Como não estou familiarizado com este pacote, vou precisar de ajuda para resolver esses problemas de hidratação. Eu criei um problema para lidar com isso.

**Comment by thauska** [comment]
Consegue mandar o print do erro?!

**Comment by Kenny4297** [comment]
![Screenshot Capture - 2024-03-03 - 10-36-24](https://github.com/devsnorte/devsnorte-landing-page/assets/97119018/6eb414a6-f48f-4bdf-8bef-3ff4e6e818a2)

**Comment by Kenny4297** [comment]
Acredito que resolvi o problema. Vou criar um PR explicando como fiz isso no problema que criei.

**Comment by Kenny4297** [comment]
Acredito que resolvi os problemas de hidratação. Vou criar um PR explicando como fiz isso no problema que criei.
