### ISSUE TITLE
bug galeria não está carregando

### ISSUE THREAD

**Issue by juanrtalmeida** [devsnorte/devsnorte-landing-page#55]
![image](https://github.com/devsnorte/devsnorte-landing-page/assets/75220133/4bc64741-5407-4fa8-a6a8-f502a7a3be17)

**Comment by juanrtalmeida** [comment]
Alguem consegue ver se isso ta acontecendo ai também? alguns reloads meus carregam a galeria e outros não (produção)

**Comment by ecsistem** [comment]
Estranho, pq aqui tá pegando. Uma coisa q achei estranho que teve momento que a animação pegou nas outras seções e parou

**Comment by juanrtalmeida** [comment]
@ecsistem isso em prod ou dev? Pq em dev tb notei q dps q um estado atualiza a aplicação recarrega e as animações aparecem.

**Comment by ecsistem** [comment]
@juanrtalmeida  em Dev apareceu, em prod o único que estava funcionando era da galeria

**Comment by juanrtalmeida** [comment]
Pode ser alguma coisa aqui q n tá carregando, vou fechar e se mais gente notar abrem
