### ISSUE TITLE
Tema claro

### ISSUE THREAD

**Issue by TiagoDanin** [devsnorte/devsnorte-landing-page#59]
Séria uma boa adicionar um tema claro, o que acham?

**Comment by Kenny4297** [comment]
Oi @TiagoDanin, acredito que posso ajudar com este problema, você se importaria de me atribuir a ele? Além disso, gostaria de saber quais são as suas cores preferidas para o tema claro.

**Comment by iagocavalcante** [comment]
Acho que é valido, só tem que ver as questões de contraste pra não distoar tanto

**Comment by Kenny4297** [comment]
Ok, vou usar Variáveis CSS com um esquema de cores básico que você pode alterar se quiser. Obrigado!

**Comment by iagocavalcante** [comment]
Boa! Vai nessa

**Comment by iagocavalcante** [comment]
resolved #60
