### ISSUE TITLE
Mover sessão do Sympla

### ISSUE THREAD

**Issue by DaywisonSilva** [devsnorte/devsnorte-landing-page#6]
A sessão do sympla deve ser a ultima sessão do site, ficando abaixo da sessão de "Sorteios"

![image](https://github.com/devsnorte/devsnorte-landing-page/assets/54292958/190afa87-7ee1-4c83-8fdf-1bf3b8f3b27e)

**Comment by ecsistem** [comment]
Estou fazendo e irei alterar a imagem e cor para ficar na paleta da DevsNorte

**Comment by thauska** [comment]
Show, @ecsistem. Já te atribuímos a atividade

**Comment by iagocavalcante** [comment]
resolved #14

**Comment by thauska** [comment]
@all-contributors add @DaywisonSilva for design
