### ISSUE TITLE
Responsividade

### ISSUE THREAD

**Issue by DaywisonSilva** [devsnorte/devsnorte-landing-page#7]
Layout da página está quebrando em certas resoluções, ocasionando scroll horizontal.
![image](https://github.com/devsnorte/devsnorte-landing-page/assets/54292958/40502890-701d-4582-a715-ee745166564a)

**Comment by juanrtalmeida** [comment]
Assinando pra mim

**Comment by iagocavalcante** [comment]
resolved #12
