### ISSUE TITLE
Erros de Hidratação com o pacote i18Next

### ISSUE THREAD

**Issue by Kenny4297** [devsnorte/devsnorte-landing-page#73]
## Descrição do Problema
Quando a aplicação é executada, você verá um erro de hidratação referente à maioria, senão a todo o código, que lida com o pacote i18Next.

![Screenshot Capture - 2024-03-03 - 10-36-24](https://github.com/devsnorte/devsnorte-landing-page/assets/97119018/46488431-8c90-4dc7-8b77-34caf2f22146)

## Como Resolver
Eu tentei adicionar uma propriedade "suppressHydrationWarning" em cada um dos erros, mas isso se provou muito trabalhoso, já que teria que ser adicionado em cada local onde o pacote está sendo utilizado.

**Comment by iagocavalcante** [comment]
solved #74

**Comment by thauska** [comment]
Thank you for your help! @holopin-bot @Kenny4297
