### ISSUE TITLE
Em parcerias colocar a logo no lugar do texto 

### ISSUE THREAD

**Issue by ecsistem** [devsnorte/devsnorte-landing-page#77]

**Comment by cleisoncarlos** [comment]
![Screenshot 2024-10-01 at 18-15-10 Devs Norte](https://github.com/user-attachments/assets/5b1ccad7-637a-46bc-ab93-68743d0a14fa)

coloquei as logos dos parceiros não estão todas padronizadas, alem disso tem a questão das cores, esta em um background escuro, como vcs acham que eu poderia fazer ???

**Comment by cleisoncarlos** [comment]
![Screenshot 2024-10-02 at 09-59-42 Devs Norte](https://github.com/user-attachments/assets/e3857864-7be7-459b-a067-e1da6dae8ec7)
