### ISSUE TITLE
Incluir na sessão do Sympla, os eventos passados

### ISSUE THREAD

**Issue by thauska** [devsnorte/devsnorte-landing-page#8]
Atualmente, temos 2 páginas de informações de eventos:
[https://www.sympla.com.br/produtor/devsnorte](https://www.sympla.com.br/produtor/devsnorte)
[https://www.sympla.com.br/produtor/devsnorte1](https://www.sympla.com.br/produtor/devsnorte1)

É interessantes incluir uma aba onde listará os eventos que já foram realizados.

![image](https://github.com/devsnorte/devsnorte-landing-page/assets/8525721/ee0a04a9-7a70-4b33-8b2d-45db5d229517)

**Comment by ecsistem** [comment]
Irei fazer

**Comment by ecsistem** [comment]
Uma aba ou sessão mesmo?

**Comment by thauska** [comment]
Uma aba mesmo, para manter nessa mesma sessão
