### ISSUE TITLE
Atualizar README

### ISSUE THREAD

**Issue by thauska** [devsnorte/devsnorte-landing-page#9]
Melhorar o README para que fique mais apresentável e, principalmente, ter uma sessão com os contribuidores.

Sugestão:
[https://github.com/devsnorte/cosmopolitan/blob/main/README.md](https://github.com/devsnorte/cosmopolitan/blob/main/README.md)

**Comment by ecsistem** [comment]
Estou fazendo

**Comment by iagocavalcante** [comment]
resolved #14

**Comment by thauska** [comment]
@all-contributors please add @ecsistem for code

**Comment by thauska** [comment]
https://github.com/all-contributors please add @iagocavalcante for Reviewed Pull Requests

**Comment by thauska** [comment]
@all-contributors
please add @thauska for Reviewed Pull Requests
please add @iagocavalcante for Reviewed Pull Requests

**Comment by thauska** [comment]
@all-contributors
please add @thauska for review
please add @iagocavalcante for review
