### ISSUE TITLE
Button shouldn't be placed center of the events section

### ISSUE THREAD

**Issue by saadman-galib** [devsnorte/devsnorte-landing-page#94]
On the website events section buttons are showing the center of the page. It shouldn't show on center in desktop mode
![image](https://github.com/devsnorte/devsnorte-landing-page/assets/73209315/119c4750-6ab5-4958-9d40-19dc417e822a)

**Comment by saadman-galib** [comment]
I would like to work on this issue

**Comment by thauska** [comment]
assigned to you
