### ISSUE TITLE
Gallery last image should not show the next button

### ISSUE THREAD

**Issue by saadman-galib** [devsnorte/devsnorte-landing-page#95]
On the website, the gallery section's first image should not show the previous button and the last image should not show the next button. 
![image](https://github.com/devsnorte/devsnorte-landing-page/assets/73209315/b4725852-ad3c-4467-84c0-f29d366f0828)

**Comment by saadman-galib** [comment]
I would like to work on this issue

**Comment by thauska** [comment]
Thanks a lot.
